---
abstract: 'easy testing for XML'
author:
  - 'Joe McMahon, E<lt>mcmahon@cpan.orgE<gt>'
build_requires: {}
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4234, CPAN::Meta::Converter version 2.150010'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-XML-Simple
provides:
  Test::XML::Simple:
    file: lib/Test/XML/Simple.pm
    version: '1.06'
requires:
  Test::Builder: '0'
  Test::Builder::Tester: '0'
  Test::LongString: '0'
  Test::More: '0'
  XML::LibXML: '1.99'
resources:
  license: http://www.perlfoundation.org/artistic_license_1_0
version: '1.06'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
